index:
    path: /
    controller: App\Controller\RegistrationController::register
home:
    path: /home
    controller: App\Controller\QuizzController::index
quizz_show:
    path: /quizz/{id}
    controller: App\Controller\QuizzController::showQuizz
question_show:
    path: /quizz/{id}/{id_question}
    controller: App\Controller\QuizzController::showQuestion
question_response:
    path: /quizz/response/{id}/{id_question}/{response}
    controller: App\Controller\QuizzController::response
profile:
    path: /profile
    controller: App\Controller\ScoreController::showProfile
quizz_create:
    path: /quizzCreate
    controller: App\Controller\QuizzController::createQuizz
quizz_send:
    path: /quizzSend
    controller: App\Controller\QuizzController::sendQuizz
new_mail:
    path: /newMail
    controller: App\Controller\SecurityController::newMail
new_pass:
    path: /newPass
    controller: App\Controller\SecurityController::newPass
admin:
    path: /admin
    controller: App\Controller\AdminController::index
user_list:
    path: /admin/userList
    controller: App\Controller\AdminController::userList
admin_list:
    path: /admin/adminList
    controller: App\Controller\AdminController::adminList
admin_profile:
    path: /admin/profile/{id}
    controller: App\Controller\AdminController::showProfile
admin_quizz_info:
    path: /admin/quizzInfo
    controller: App\Controller\AdminController::quizzInfo
admin_quizz:
    path: /admin/quizz/{id}
    controller: App\Controller\AdminController::showQuizz
admin_quizz_list:
    path: /admin/quizzList
    controller: App\Controller\AdminController::quizzList
admin_delete_quizz:
    path: /admin/deleteQuizz/{id}
    controller: App\Controller\AdminController::deleteQuizz
create_admin:
    path: /admin/createAdmin
    controller: App\Controller\AdminController::createAdmin
delete_user:
    path: /admin/deleteUser/{id}
    controller: App\Controller\AdminController::deleteUser
admin_question:
    path: /admin/question/{id}
    controller: App\Controller\AdminController::showQuestion
